list=[0,1,2,3]
print("List is:", list)
list.append(5)
print("List after appending: ",list)
list.extend([7,8,9])
print("List after extending: ",list)
list.remove(2)
print("List after removing 2: ",list)
list.reverse()
print("list after reversing: ",list)
list.sort()
print("List after sorting: ",list)
list.sort(reverse=True)
print(list)